{"timestamp":"2025-06-13T11:31:59.810885","level":"info","event":"DAG bundles loaded: dags-folder","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager"}
{"timestamp":"2025-06-13T11:31:59.815981","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/dag.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-06-13T11:32:00.291821","level":"info","event":"Secrets backends loaded for worker","count":1,"backend_classes":["EnvironmentVariablesBackend"],"logger":"supervisor"}
{"timestamp":"2025-06-13T11:32:00.402652","level":"info","event":"Connection Retrieved 'TEST'","logger":"airflow.hooks.base"}
{"timestamp":"2025-06-13T11:32:00.464381Z","level":"error","event":"%3|1749814320.463|FAIL|rdkafka#consumer-1| [thrd:host.docker.internal:29092/bootstrap]: host.docker.internal:29092/bootstrap: Connect to ipv4#192.168.65.254:29092 failed: Connection refused (after 40ms in state CONNECT)","chan":"stderr","logger":"task"}
{"timestamp":"2025-06-13T11:32:00.466420Z","level":"info","event":"Exception received:  KafkaError{code=_TRANSPORT,val=-195,str=\"host.docker.internal:29092/bootstrap: Connect to ipv4#192.168.65.254:29092 failed: Connection refused (after 40ms in state CONNECT)\"}","chan":"stdout","logger":"task"}
{"timestamp":"2025-06-13T11:32:00.468101Z","level":"info","event":"Exception received:  KafkaError{code=_ALL_BROKERS_DOWN,val=-187,str=\"1/1 brokers are down\"}","chan":"stdout","logger":"task"}
{"timestamp":"2025-06-13T11:32:00.477625Z","level":"error","event":"%3|1749814320.477|FAIL|rdkafka#consumer-1| [thrd:host.docker.internal:29092/bootstrap]: host.docker.internal:29092/bootstrap: Connect to ipv4#192.168.65.254:29092 failed: Connection refused (after 2ms in state CONNECT, 1 identical error(s) suppressed)","chan":"stderr","logger":"task"}
{"timestamp":"2025-06-13T11:32:00.478375Z","level":"info","event":"Exception received:  KafkaError{code=_TRANSPORT,val=-195,str=\"host.docker.internal:29092/bootstrap: Connect to ipv4#192.168.65.254:29092 failed: Connection refused (after 2ms in state CONNECT, 1 identical error(s) suppressed)\"}","chan":"stdout","logger":"task"}
{"timestamp":"2025-06-13T11:32:30.520516Z","level":"error","event":"%3|1749814350.511|FAIL|rdkafka#consumer-1| [thrd:host.docker.internal:29092/bootstrap]: host.docker.internal:29092/bootstrap: Connect to ipv4#192.168.65.254:29092 failed: Connection refused (after 10ms in state CONNECT, 554 identical error(s) suppressed)","chan":"stderr","logger":"task"}
{"timestamp":"2025-06-13T11:32:30.572849Z","level":"info","event":"Exception received:  KafkaError{code=_TRANSPORT,val=-195,str=\"host.docker.internal:29092/bootstrap: Connect to ipv4#192.168.65.254:29092 failed: Connection refused (after 10ms in state CONNECT, 554 identical error(s) suppressed)\"}","chan":"stdout","logger":"task"}
{"timestamp":"2025-06-13T11:33:00.443358","level":"info","event":"Reached end of log. Exiting.","logger":"airflow.task.operators.airflow.providers.apache.kafka.operators.consume.ConsumeFromTopicOperator"}
{"timestamp":"2025-06-13T11:33:00.447305","level":"info","event":"committing offset at end_of_operator","logger":"airflow.task.operators.airflow.providers.apache.kafka.operators.consume.ConsumeFromTopicOperator"}
